version: "2"

services:
  tensorflow:
    build: ./containers/tensorflow
    volumes:
      - "./data/script:/notebooks/script"
      - "./data/doc:/notebooks/data"
    ports:
      - 8888:8888
      - 6006:6006
