version: "2"

services:
  tensorflow:
    build: ./containers/tensorflow
    volumes:
      - "./containers/tensorflow/scripts:/notebooks/scripts"
      - "./containers/tensorflow/data:/notebooks/data"
    ports:
      - 8888:8888
      - 6006:6006
