version: "2"

services:
  spark:
    build: ./containers/spark
    volumes:
      - "./data/html:/usr/local/apache2/cgi-bin"
      - "./data/log:/usr/local/apache2/logs"
      - "./data/script:/usr/local/apache2/script"
      - "./data/config:/usr/local/lib/spark/conf"
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      - 4040:4040
      - 7077:7077
    tty: true