version: "2"

services:
  spark:
    build: ./containers/spark
    volumes:
      - "./data/log:/usr/local/lib/spark/logs"
      - "./data/script:/usr/local/lib/spark/script"
      - "./data/config:/usr/local/lib/spark/conf"
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
      - 443:443
      - 4040:4040
      - 7077:7077
    tty: true