# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "private_network", type: "dhcp"
  #http
  config.vm.network "forwarded_port", guest: 80, host: 8080
  #socket
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.synced_folder "./", "/home/vagrant/spark", owner: "vagrant", group: "vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.gui = true
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker
    apt-get install -y docker-compose
    dpkg-reconfigure tzdata
  SHELL
  config.vm.provision "shell", run: "always", inline: "cd /home/vagrant/spark && docker-compose start 1>&2"
end
