version: "2"

services:
  apache:
    build: ./containers/apache
    volumes:
      - "./data/html:/usr/local/apache2/cgi-bin"
      - "./data/log:/usr/local/apache2/logs"
    ports:
      - 80:80
      - 443:443
#    links:
#      - perl
#    links:
#      - mysql
  mysql:
    build: ./containers/mysql
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./log:/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: ryouzi01
      MYSQL_USER: abot
      MYSQL_DB: abot
    expose:
     - "3306"
#  perl:
#    build: ./containers/perl
#    links:
#      - mysql
