FROM gcr.io/tensorflow/tensorflow:1.3.0-py3
RUN cd ~/ && ln -s /notebooks tensorflow
#use https://github.com/tensorflow/models/tree/master/object_detection
#RUN ["pip",  "install", "tensorflow-gpu"]
#RUN ["pip",  "install", "lxml"]